boxbot:
  # Publish all joint states----------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers -------------------------------------------
  left_joint_1_controller:
    type: position_controllers/JointPositionController
    joint: left_joint_1
    pid: {p: 50.0, i: 0.1, d: 1.0}

  left_joint_2_controller:
    type: position_controllers/JointPositionController
    joint: left_joint_2
    pid: {p: 50.0, i: 0.1, d: 1.0}

  left_joint_3_controller:
    type: position_controllers/JointPositionController
    joint: left_joint_3
    pid: {p: 50.0, i: 0.1, d: 1.0}

  left_joint_4_controller:
    type: position_controllers/JointPositionController
    joint: left_joint_4
    pid: {p: 50.0, i: 0.1, d: 1.0}

  left_joint_5_controller:
    type: position_controllers/JointPositionController
    joint: left_joint_5
    pid: {p: 50.0, i: 0.1, d: 1.0}

  left_gripper_joint_controller:
    type: position_controllers/JointPositionController
    joint: left_gripper_joint
    pid: {p: 50.0, i: 0.1, d: 1.0}

  left_gripper_mimic_controller:
    type: position_controllers/JointPositionController
    joint: left_gripper_prismatic_joint_2
    pid: {p: 50.0, i: 0.1, d: 1.0}


  right_joint_1_controller:
    type: position_controllers/JointPositionController
    joint: right_joint_1
    pid: {p: 50.0, i: 0.1, d: 1.0}

  right_joint_2_controller:
    type: position_controllers/JointPositionController
    joint: right_joint_2
    pid: {p: 50.0, i: 0.1, d: 1.0}

  right_joint_3_controller:
    type: position_controllers/JointPositionController
    joint: right_joint_3
    pid: {p: 50.0, i: 0.1, d: 1.0}

  right_joint_4_controller:
    type: position_controllers/JointPositionController
    joint: right_joint_4
    pid: {p: 50.0, i: 0.1, d: 1.0}

  right_joint_5_controller:
    type: position_controllers/JointPositionController
    joint: right_joint_5
    pid: {p: 50.0, i: 0.1, d: 1.0}

  right_gripper_joint_controller:
    type: position_controllers/JointPositionController
    joint: right_gripper_joint
    pid: {p: 50.0, i: 0.1, d: 1.0}

  right_gripper_mimic_controller:
    type: position_controllers/JointPositionController
    joint: right_gripper_prismatic_joint_2
    pid: {p: 50.0, i: 0.1, d: 1.0}
