boxbot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  left_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5

  left_gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_gripper_joint

  right_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5

  right_gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - right_gripper_joint

  # "Fake" Scaled Position Controllers

  left_fake_gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_gripper_prismatic_joint_2

  right_fake_gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_gripper_prismatic_joint_2
  
